package com.dayee.wintalent.service.v8;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-21T12:51:55.029+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://v8.service.wintalent.dayee.com", name = "externalResumeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ExternalResumeServicePortType {

    @WebMethod
    @RequestWrapper(localName = "entryStatus", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.EntryStatus")
    @ResponseWrapper(localName = "entryStatusResponse", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.EntryStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://v8.service.wintalent.dayee.com")
    public java.lang.String entryStatus(
        @WebParam(name = "in0", targetNamespace = "http://v8.service.wintalent.dayee.com")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "callbackToChangeStatus", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.CallbackToChangeStatus")
    @ResponseWrapper(localName = "callbackToChangeStatusResponse", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.CallbackToChangeStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://v8.service.wintalent.dayee.com")
    public java.lang.String callbackToChangeStatus(
        @WebParam(name = "in0", targetNamespace = "http://v8.service.wintalent.dayee.com")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "readEntryInformation", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.ReadEntryInformation")
    @ResponseWrapper(localName = "readEntryInformationResponse", targetNamespace = "http://v8.service.wintalent.dayee.com", className = "com.dayee.wintalent.service.v8.ReadEntryInformationResponse")
    @WebResult(name = "out", targetNamespace = "http://v8.service.wintalent.dayee.com")
    public java.lang.String readEntryInformation(
        @WebParam(name = "in0", targetNamespace = "http://v8.service.wintalent.dayee.com")
        java.lang.String in0
    );
}
